baseURL = "http://localhost:1313/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "鹊木笔记"                        # site title                     # 网站标题
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 4                           # shows the number of articles   # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                   # your google analytics id       # Google统计代码

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]                               # essential                      # 必需
  name = "awesome404"

[blackfriday]
  smartypants = false

[[menu.main]]                          # config your menu               # 配置菜单
  name = "首页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "关于"
  weight = 40
  identifier = "about"
  url = "/about/"

[params]
  subTitle = "前端菜鸡的自我修养"                                       # site's subTitle              # 网站二级标题
  keywords = ["Blog","程序员","前端"]                                   # site's keywords              # 网站关键字
  description = "一名前端程序员的博客!!!"                        # site's description           # 网站描述
  enableMathJax = false                                                 # enable mathjax               # 是否使用mathjax（数学公式）
  enableSummary = true                                                 # display the article summary  # 是否显示文章摘要
  mainSections = ["posts","post"]
  
# 考虑改用其他评论插件 comments.html
# Valine.
[params.valine]
  enable = false
  appId = "A6e8lHE5aJjGEYKcaf0aUY9e-gzGzoHsz"
  appKey = "Xap1oHAAawXWikHbCNzRbPuu"
  placeholder = "欢迎评论!"
  visitor = true

# Your socail's url
# 社交地址配置
[social]
  github = "https://github.com/404Awesome"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
